### ISSUE TITLE
v0.5.1 release binaries missing

### ISSUE THREAD

**Issue by rdsubhas** [jmatsu/terraform-provider-slack#23]
Hi @jmatsu, thank you a ton for this amazing provider :) Just wanted to say that the `v0.5.1` release doesn't have the binary files uploaded in github releases. Cheers and stay safe!

**Comment by jmatsu** [comment]
I'm very sorry. I've fixed the deployment just now. Thanks for your report!

**Comment by rdsubhas** [comment]
that was fast, thank you so much @jmatsu!
