### ISSUE TITLE
Release on registry.terraform.io

### ISSUE THREAD

**Issue by bewiwi** [jmatsu/terraform-provider-slack#35]
Hi !
With terraform 0.13 it's now possible for the community to [release provider in terraform provider registry](https://registry.terraform.io/publish/provider). 
Is it plan to publish this provider in the official registry?

**Comment by jmatsu** [comment]
I didn't know the new community support 👀  Let me check it.

**Comment by jmatsu** [comment]
noted https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by jmatsu** [comment]
Dit it! https://registry.terraform.io/providers/jmatsu/slack/latest
