### ISSUE TITLE
Add documentation for HashiCorp Registry

### ISSUE THREAD

**Issue by Gowiem** [jmatsu/terraform-provider-slack#40]
This provider looks like the best Slack provider around, so I'm excited to use it. However, the documentation is only available via the README, which is lacking. It would be great if this were properly documented similar to other providers via the documentation tab in the provider registry: https://registry.terraform.io/providers/jmatsu/slack/latest

**Comment by Gowiem** [comment]
@jmatsu is this something you're continuing to work on?

**Comment by Gowiem** [comment]
Ah seems @oliverisaac is all over this via #39. @jmatsu maybe we can get that merged?

**Comment by jmatsu** [comment]
Sorry for the late response. The documentation is available now. Thank you @oliverisaac !

https://registry.terraform.io/providers/jmatsu/slack/latest/docs
