### ISSUE TITLE
Channels deleted by provider can't be recreated without manual intervention

### ISSUE THREAD

**Issue by gregswift** [jmatsu/terraform-provider-slack#41]
We attempted to tear down and rebuild after getting everything setup.  The delete method only archives the channel, so when we tried to re-create it we got an error that the channel already existed and the terraform run failed.

To fix it we have a Slack Admin actually delete the channel, and then the create run worked.

**Comment by jmatsu** [comment]
I'm sorry, I cannot test Admin scope API because I'm not joining any Enterprise Grid workspaces. 

Contributions are welcome of course!

ref: https://api.slack.com/methods/admin.conversations.delete

**Comment by gregswift** [comment]
We aren't enterprise grid either

**Comment by jmatsu** [comment]
Oh, yes, you are right. Sorry for my misunderstanding. 

The problem is that this provider's destroy behaviour, i.e. archiving channels, is a violation of terraform's philosophy. We have to drop destroy action for channels, and consider some cases like users try to create duplicated channels.

**Comment by gregswift** [comment]
Maybe just add a flag for enterprise customers to be able to fully delete (which neither of us can test 😅)but otherwise have destroy just archive and have create revive an archived channel if it exists?

Then docs can just state that behavior and reference the manual work due to Slack's limitations?

**Comment by jmatsu** [comment]
conversation, group, and channel resources require a new `action_on_destroy` field. Please set `none` to it to solve this issue. Thank you for your report!
