### ISSUE TITLE
Invite members from other orgs into a channel resource.

### ISSUE THREAD

**Issue by UjjwalKarn954** [jmatsu/terraform-provider-slack#54]
I want to send invite to people from other organisations so that we can communicate together as we do in our organisation.

As a user of Organisation: A
Want to send invite to someone from organisation: B.

How can I achieve this?

**Comment by jmatsu** [comment]
@UjjwalKarn954 
Sending invitations requires Slack Enterprise Grid plan and this provider does not support the plan. 
BTW, terraform resource management sounds inappropriate for your use case. It would be better if you can consider using Slack workflows and Slack APIs directly.
