### ISSUE TITLE
restricted_action error when changing  slack channel  name/topic/description

### ISSUE THREAD

**Issue by qxmips** [jmatsu/terraform-provider-slack#55]
got restricted_action error when  changing channel name, after it was created with this module. though the  changes are applied.

```
resource "slack_conversation" "channel" {
  name              = local.slack_channels
  topic = "alerts for ${var.es_cluster_name}"
  purpose = "alerts for 123 ${var.es_cluster_name}"
  action_on_destroy = "none"
  is_archived = false
  is_private = false
}
```
scope that used with the token:

```
  scopes:
    user:
      - channels:read
      - channels:write
      - groups:read
      - groups:write
      - users:read
      - usergroups:read
      - usergroups:write
      - users:read.email
```

tf debug logs:

```
2021/12/16 15:15:04 [DEBUG] module.looking_glass.module.monitoring.slack_conversation.channel: apply errored, but we're indicating that via the Error pointer rather than returning it: restricted_action
2021/12/16 15:15:04 [ERROR] eval: *terraform.EvalApplyPost, err: restricted_action
2021/12/16 15:15:04 [ERROR] eval: *terraform.EvalSequence, err: restricted_action
```

**Comment by jmatsu** [comment]
@qxmips 
The message is shown when your API token doesn't contain enough permission or the token type is not supported. Have you confirmed if `conversations.create` API requests with the token succeeded?

ref:
- https://api.slack.com/scopes/channels:write
- https://api.slack.com/methods/conversations.create

**Comment by qxmips** [comment]
yes, here is the  permissions for my token:

```
      - channels:read
      - channels:write
      - groups:read
      - groups:write
      - users:read
      - usergroups:read
      - usergroups:write
      - users:read.email
      - im:write
      - mpim:write
     ```
also same token works without errors pablovarela slack provider. Is there a way to add to debug output what permissions are missing?

**Comment by jmatsu** [comment]
@qxmips 
I don't know what APIs pablovarela's provider uses.

> Is there a way to add to debug output what permissions are missing?

The released binaries do not provide a way to change the log granularity. You have to modify the code and build a provider. FYI, please refer to the official document to use local providers.

**Comment by jmatsu** [comment]
The current official documents says the error will be shown if a team preference prevents the authenticated user from creating channels, however, I couldn't reproduce the situation. 

Please feel free to create a new issue if you get this error again.
